version: "2.0"

services:
  web:
    image: ajasibley/plurigrid-ui:latest
    env:
      - HOST=0.0.0.0
    expose:
      - port: 4173
        as: 80
        to:
          - global: true

profiles:
  compute:
    web:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 128Mi
        storage:
          size: 128Mi

deployment:
  web:
    global:
      profile: web
      count: 1
